language: ruby
rvm:
  - 1.9.3
before_install:
  - wget -P /tmp http://phantomjs.googlecode.com/files/phantomjs-1.9.0-linux-x86_64.tar.bz2
  - tar -xf /tmp/phantomjs-1.9.0-linux-x86_64.tar.bz2 -C /tmp/
  - sudo rm -rf /usr/local/phantomjs
  - sudo mv /tmp/phantomjs-1.9.0-linux-x86_64 /usr/local/phantomjs
before_script:
  - psql -c 'create database procureio_travis;' -U postgres
  - cp config/database.travis.yml config/database.yml
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
script: rspec
notifications:
  email: false
