language: ruby
rvm:
  - 1.9.3
before_script:
  - psql -c 'create database procureio_travis;' -U postgres
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:test:prepare
script: rspec